<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Formulario</title>
</head>
<body>

<form method="POST">
	<fieldset>
	    <legend>Borrar:</legend>
	    <input type="hidden" name="line" value="<?=$_GET['line']?>">
	    <ul>
			
	    	<li>Nombre: <input type="text" name="name" value="<?=(isset($user[1]))?$user[1]:'';?>"></li>
	    	<li>
	    		Seguro que desea borrar el usuario
	    	</li>
	    	<li>
	    		Si: <input type="submit" name="borrar" value="Si">
	    		No: <input type="submit" name="borrar" value="No">
	    	</li>
	    </ul>
	    
  	</fieldset>
</form>

</body>
</html>